name: trunk

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
  cancel-in-progress: true

jobs:
  macos-11-py3-x86-64-build:
    name: macos-11-py3-x86-64
    uses: ./.github/workflows/_mac-build.yml
    with:
      build-environment: macos-11-py3-x86-64
      xcode-version: "13.3.1"
      runner-type: macos-12
      build-generates-artifacts: true
    secrets:
      MACOS_SCCACHE_S3_ACCESS_KEY_ID: ${{ secrets.MACOS_SCCACHE_S3_ACCESS_KEY_ID }}
      MACOS_SCCACHE_S3_SECRET_ACCESS_KEY: ${{ secrets.MACOS_SCCACHE_S3_SECRET_ACCESS_KEY }}
